### ISSUE TITLE
Type Mutation not Found

### ISSUE THREAD

**Issue by juank11memphis** [serverless-components/aws-app-sync#11]
I have the following configuration
serverless.yml
```
signupLambda:
  component: '@serverless/aws-lambda'
  inputs:
    handler: index.signUpHandler
    code: ../../lib/components/auth
backend:
  component: '@serverless/aws-app-sync'
  inputs:
    name: mvg-dev-backend
    authenticationType: AWS_IAM

    dataSources:
      - type: AWS_LAMBDA
        name: signup
        config:
          lambdaFunctionArn: ${signupLambda.arn}

    mappingTemplates:
      - dataSource: signup
        type: Mutation
        field: signup
```

schema.graphql

```
schema {
  mutation: Mutation
}

# queries

# mutations

type Mutation {
  signup(user: UserInput): AuthResponse
}

# types

type AuthResponse {
  user: User!
  token: String!
}

type User {
  id: String!
  firstname: String
  lastname: String
  email: String
  roles: [UserRole]
}

type UserRole {
  name: String!
  permissions: [String]
}
```

When I run `serverless` I keep getting this error:

```
backend › NotFoundException: Type Mutation not found
```

Is this a bug or is it something I am doing wrong?
