### ISSUE TITLE
Deploy to another region

### ISSUE THREAD

**Issue by mdchad** [serverless-components/aws-app-sync#12]
Currently the default is us-east-1. Is there any way that I can deploy it to another region?

**Comment by laardee** [comment]
@mdchad Hi, you can define the region in inputs.

```yaml
myAppSyncApi:
  component: "@serverless/aws-app-sync"
  inputs:
    region: "eu-west-1"
    # ... rest of the inputs
```

If you are using `AWS_REGION` system environmental variable and you want to deploy to that region, you can do it following way.

```yaml
myAppSyncApi:
  component: "@serverless/aws-app-sync"
  inputs:
    region: ${env.AWS_REGION}
    # ... rest of the inputs
```

**Comment by mdchad** [comment]
@laardee thanks for the help. When I declared the region in my serverless.yml, it seems that it never gets deployed

In my terminal:

<img width="1030" alt="Screenshot 2019-10-29 at 10 26 01 AM" src="https://user-images.githubusercontent.com/2016750/67732850-a59a2a00-fa37-11e9-97eb-c8115b8da2a9.png">

Here is my serverless.yml

```
myAppSyncApi:
  component: "@serverless/aws-app-sync"
  inputs:
    apiId: 'myAPIThatImReusing' # I'm reusing existing API
    region: 'ap-southeast-1'
  mappingTemplates:
    - dataSource: 'RoomsListByLocation'
      type: 'Query'
      field: 'listRoomsByLocation'
  dataSources:
    - type: 'AWS_LAMBDA'
      name: 'RoomsListByLocation'
      config:
        lambdaFunctionArn: 'whateverMyLambdaARN'
```

**Comment by mdchad** [comment]
@laardee Thanks for the help! After I defined the region, it doesn't seem to deploy. The message keep on saying that it is 'deploying...

Here is my terminal:
<img width="1030" alt="Screenshot 2019-10-29 at 10 26 01 AM" src="https://user-images.githubusercontent.com/2016750/67744232-ec018000-fa5b-11e9-941b-3aa339df2eae.png">

and my serverless.yml
```yml
myAppSyncApi:
  component: "@serverless/aws-app-sync"
  inputs:
    apiId: 'whateverMyApiID'
    region: 'ap-southeast-1'
    mappingTemplates:
      - dataSource: 'RoomsListByLocation'
        type: 'Query'
        field: 'listRoomsByLocation'
    dataSources:
      - type: 'AWS_LAMBDA'
        name: 'RoomsListByLocation'
        config:
          lambdaFunctionArn: 'whateverMyLambdaArn'
```
