### ISSUE TITLE
Schema Concurrent Modification Error

### ISSUE THREAD

**Issue by lukevandekieft** [serverless-components/aws-app-sync#16]
I've been testing how my app fares on its initial `serverless` deploy and frequently run into a `ConcurrentModificationException` error from @serverless' aws-sdk folder:

```
  error:
  { ConcurrentModificationException: Schema is currently being altered, please wait until that is complete.
    at Object.extractError (C:\Users\Luke\.serverless\components\registry\npm\@serverless\aws-app-sync@1.2.0\node_modules\@serverless\aws-app-sync\node_modules\aws-sdk\lib\protocol\json.js:51:27)
    at Request.extractError (C:\Users\Luke\.serverless\components\registry\npm\@serverless\aws-app-sync@1.2.0\node_modules\@serverless\aws-app-sync\node_modules\aws-sdk\lib\protocol\rest_json.js:55:8)
    at Request.callListeners (C:\Users\Luke\.serverless\components\registry\npm\@serverless\aws-app-sync@1.2.0\node_modules\@serverless\aws-app-sync\node_modules\aws-sdk\lib\sequential_executor.js:106:20)
    at Request.emit (C:\Users\Luke\.serverless\components\registry\npm\@serverless\aws-app-sync@1.2.0\node_modules\@serverless\aws-app-sync\node_modules\aws-sdk\lib\sequential_executor.js:78:10)
    at Request.emit (C:\Users\Luke\.serverless\components\registry\npm\@serverless\aws-app-sync@1.2.0\node_modules\@serverless\aws-app-sync\node_modules\aws-sdk\lib\request.js:683:14)
    at Request.transition (C:\Users\Luke\.serverless\components\registry\npm\@serverless\aws-app-sync@1.2.0\node_modules\@serverless\aws-app-sync\node_modules\aws-sdk\lib\request.js:22:10)
    at AcceptorStateMachine.runTo (C:\Users\Luke\.serverless\components\registry\npm\@serverless\aws-app-sync@1.2.0\node_modules\@serverless\aws-app-sync\node_modules\aws-sdk\lib\state_machine.js:14:12)
    at C:\Users\Luke\.serverless\components\registry\npm\@serverless\aws-app-sync@1.2.0\node_modules\@serverless\aws-app-sync\node_modules\aws-sdk\lib\state_machine.js:26:10
    at Request.<anonymous> (C:\Users\Luke\.serverless\components\registry\npm\@serverless\aws-app-sync@1.2.0\node_modules\@serverless\aws-app-sync\node_modules\aws-sdk\lib\request.js:38:9)
    at Request.<anonymous> (C:\Users\Luke\.serverless\components\registry\npm\@serverless\aws-app-sync@1.2.0\node_modules\@serverless\aws-app-sync\node_modules\aws-sdk\lib\request.js:685:12)
  message:
   'Schema is currently being altered, please wait until that is complete.',
  code: 'ConcurrentModificationException',
  time: 2019-11-27T00:02:17.608Z,
  requestId: 'dfb62d88-4a10-45da-9d26-603d667e5a2c',
  statusCode: 409,
  retryable: false,
  retryDelay: 75.52683412422829 }

  26s » appsync » ConcurrentModificationException: Schema is currently being altered, please wait until that is complete.
```

Occasionally it will deploy successfully but typically it will stop with the above. The AppSync schema will be half-finished with 1-4 resolvers not attached (they change each time) but running `serverless` a second time will fix them and complete setup.

This is thankfully not a breaking error as the second `serverless` command fixes it but I'm curious why it doesn't work on the first try. I haven't gotten this error when using a single data source so I wonder if having multiple DynamoDB tables is causing this?

My setup is as follows:

`serverless.yml`
```
todoTable:
  component: '@serverless/aws-dynamodb'
  inputs:
    name: todo-table

userTable:
  component: '@serverless/aws-dynamodb'
  inputs:
    name: user-table

appsync:
  component: '@serverless/aws-app-sync'
  inputs:
    name: dynamodb-template
    authenticationType: API_KEY
    apiKeys:
      - myApiKey
    dataSources:
      - type: AMAZON_DYNAMODB
        name: Todos
        config:
          tableName: ${todoTable.name}
      - type: AMAZON_DYNAMODB
        name: Users
        config:
          tableName: ${userTable.name}
    mappingTemplates:
      - dataSource: Todos
        type: Query
        field: getTodo
        request: mapping-templates/request/dynamodb/get.vtl
        response: mapping-templates/response/dynamodb/generic.vtl
      - dataSource: Todos
        type: Query
        field: getTodos
        request: mapping-templates/request/dynamodb/scan.vtl
        response: mapping-templates/response/dynamodb/scan.vtl
      - dataSource: Todos
        type: Mutation
        field: addTodo
        request: mapping-templates/request/dynamodb/put.vtl
        response: mapping-templates/response/dynamodb/generic.vtl
      - dataSource: Todos
        type: Mutation
        field: deleteTodo
        request: mapping-templates/request/dynamodb/delete.vtl
        response: mapping-templates/response/dynamodb/generic.vtl
      - dataSource: Todos
        type: Mutation
        field: updateTodo
        request: mapping-templates/request/dynamodb/update.vtl
        response: mapping-templates/response/dynamodb/generic.vtl
      - dataSource: Users
        type: Query
        field: getUser
        request: mapping-templates/request/dynamodb/get.vtl
        response: mapping-templates/response/dynamodb/generic.vtl
      - dataSource: Users
        type: Query
        field: getUsers
        request: mapping-templates/request/dynamodb/scan.vtl
        response: mapping-templates/response/dynamodb/scan.vtl
      - dataSource: Users
        type: Mutation
        field: addUser
        request: mapping-templates/request/dynamodb/put.vtl
        response: mapping-templates/response/dynamodb/generic.vtl
      - dataSource: Users
        type: Mutation
        field: deleteUser
        request: mapping-templates/request/dynamodb/delete.vtl
        response: mapping-templates/response/dynamodb/generic.vtl
      - dataSource: Users
        type: Mutation
        field: updateUser
        request: mapping-templates/request/dynamodb/update.vtl
        response: mapping-templates/response/dynamodb/generic.vtl
```

`schema.graphql`
```
schema {
  query: Query
  mutation: Mutation
}

type Query {
  getTodos: [Todo]
  getTodo(id: ID!): Todo
  getUsers: [User]
  getUser(id: ID!): User
}

type Mutation {
  addTodo(input: TodoInput!): Todo
  updateTodo(input: TodoInput!): Todo
  deleteTodo(input: TodoInput!): Todo
  addUser(input: UserInput!): User
  updateUser(input: UserInput!): User
  deleteUser(input: UserInput!): User
}

type Todo {
  id: ID!
  name: String
  description: String
}

input TodoInput {
  id: ID!
  name: String
  description: String
}

type User {
  id: ID!
  name: String
  title: String
}

input UserInput {
  id: ID!
  name: String
  title: String
}
```
