### ISSUE TITLE
Support for additional authentication types?

### ISSUE THREAD

**Issue by vicary** [serverless-components/aws-app-sync#21]
A proper GraphQL API usually requires more than one authentication types.

AppSync actually lets users adding multiple additional authentication types where developers can specify in their schema via @auth_ directives.

Does this component support that?

**Comment by EphemeralX** [comment]
I had this same question and after dugging through the source code and some trial and error, came up with this which worked:
```
inputs:
    name: RushDraft-Test
    region: us-east-2
    authenticationType: API_KEY
    apiKeys:
      - myApiKey
    additionalAuthenticationProviders:
      - authenticationType: AMAZON_COGNITO_USER_POOLS
        userPoolConfig:
          awsRegion: 'us-east-2'
          userPoolId: 'us-east-2_JqMnOR9nz'
```
