### ISSUE TITLE
AppSync is not removed with sls remove

### ISSUE THREAD

**Issue by JohnAtFenestra** [serverless-components/aws-app-sync#26]
Very simple test application. 

serverless.yml
```yaml
elrickTestLambda:
  component: "@serverless/aws-lambda"
  inputs:
    name: elrickTestLambda
    description: A Test Lambda for serverless deployment
    handler: index.handler
    code: ./code
    runtime: nodejs12.x
    region: us-east-2

elrickTestAppSyncApi:
  component: "@serverless/aws-app-sync"
  inputs:
    # creating the API and an API key
    name: elrickTestPosts
    authenticationType: API_KEY
    region: us-east-2
    apiKeys:
      - the api key

    # defining your lambda data source
    dataSources:
      - type: AWS_LAMBDA
        name: getPost
        config:
          lambdaFunctionArn: ${elrickTestLambda.arn}

    # mapping schema fields to the data source
    mappingTemplates:
      - dataSource: getPost
        type: Query
        field: getPost
        request: request.vtl
```

request.vtl
```
{
  "version": "2017-02-28",
  "operation": "Invoke",
  "payload": $util.toJson($context.arguments)
}
```

code/index.js
```javascript
exports.handler = async event => {
  const posts = {
    "1": {
      id: "1",
      title: "First Blog Post",
      author: "Eetu Tuomala",
      url: "https://serverless.com/",
      content:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s."
    },
    "2": {
      id: "2",
      title: "Second Blog Post",
      author: "Siddharth Gupta",
      url: "https://serverless.com",
      content:
        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s."
    }
  };

  return posts[event.id];
};
```
schema.graphql
```
schema {
  query: Query
}

type Query {
  getPost(id: ID!): Post
}

type Post {
  id: ID!
  author: String!
  title: String
  content: String
  url: String
}
```

Deploy with `sls` then run `sls remove`. The Lambda is removed but the AppSync instance must be deleted by hand.
